import * as Linking from "expo-linking";
import { router } from "expo-router";
import { Pressable,StyleSheet,View } from "react-native";
import { AppScreen,AppText,Card,MutedText,PrimaryButton,SectionTitle } from "@/components/ui";
import { useAuth } from "@/contexts/auth";
import { useEmpire } from "@/contexts/empire";
import { useEmpireTheme } from "@/contexts/theme";
import type { ColorMode } from "@/types/api";
export default function SettingsScreen(){const {session,signOut}=useAuth();const {bootstrap,direction,locale,setLocale}=useEmpire();const {colors,mode,setMode}=useEmpireTheme();const ar=direction==="rtl";return <AppScreen><SectionTitle eyebrow="APP" title={ar?"الإعدادات":"Settings"} description={ar?"اللغة والمظهر والحساب.":"Language, appearance, and account."}/><Card><AppText style={styles.title}>{ar?"المظهر":"Appearance"}</AppText><View style={styles.options}>{(["light","dark","system"] as ColorMode[]).map(item=><OptionButton key={item} label={item==="light"?(ar?"فاتح":"Light"):item==="dark"?(ar?"داكن":"Dark"):(ar?"النظام":"System")} active={mode===item} onPress={()=>void setMode(item)}/>)}</View></Card><Card><AppText style={styles.title}>{ar?"اللغة":"Language"}</AppText><View style={styles.options}>{(bootstrap?.locales??[]).map(item=><OptionButton key={item.code} label={item.nativeName} active={locale===item.code} onPress={()=>void setLocale(item.code)}/>)}</View></Card><Card><AppText style={styles.title}>{ar?"الموقع":"Website"}</AppText><MutedText>webempire.site</MutedText><PrimaryButton label={ar?"فتح الموقع":"Open website"} onPress={()=>void Linking.openURL(`https://webempire.site/${locale}`)}/></Card><Card><AppText style={styles.title}>{ar?"الحساب":"Account"}</AppText><MutedText>{session?.user.email??(ar?"لم تسجل الدخول":"Not signed in")}</MutedText>{session?<PrimaryButton label={ar?"تسجيل الخروج":"Sign out"} onPress={()=>void signOut()}/>:<PrimaryButton label={ar?"تسجيل الدخول":"Sign in"} onPress={()=>router.push("/sign-in")}/>}</Card><MutedText style={{textAlign:"center",color:colors.muted}}>Web Empire Mobile 1.0.0</MutedText></AppScreen>}
function OptionButton({label,active,onPress}:{label:string;active:boolean;onPress():void}){const {colors}=useEmpireTheme();return <Pressable onPress={onPress} style={[styles.option,{backgroundColor:active?colors.primary:colors.background,borderColor:active?colors.primary:colors.border}]}><AppText style={{color:active?"#fff":colors.text,fontWeight:"800",fontSize:13}}>{label}</AppText></Pressable>}
const styles=StyleSheet.create({title:{fontSize:19,fontWeight:"900"},options:{flexDirection:"row",flexWrap:"wrap",gap:8},option:{borderWidth:1,borderRadius:999,paddingHorizontal:14,paddingVertical:9}});
